spring:
  main: # потом попробовать без этого
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        like-channel:
          name: like_channel
        calculations-channel:
          name: calculations_channel
        user-ban-channel:
          name: user_ban_channel
        comment-channel:
          name: comment_channel
        post-view-channel:
          name: post_view_channel

    kafka:
      bootstrap-servers: localhost:9092
      topic:
        post-topic:
          name: posts
          partitions: 1
          replicationFactor: 1
        comment-topic:
          name: comments
          partitions: 1
          replicationFactor: 1
        like-topic:
          name: likes
          partitions: 1
          replicationFactor: 1
        post-view-topic:
          name: post_views
          partitions: 1
          replicationFactor: 1
      producer:
        retry:
          maxAttempts: 3
          backOffDelay: 1
        executor:
          core-pool-size: 100
          max-pool-size: 500
          queue-capacity: 10000
          thread-name-prefix: ProducerThread-
        producers:
          post:
            limit-amount-user-ids: 10000
      consumer:
        comment-consumer:
          group-id: "comments"
        post-consumer:
          group-id: "posts"
        like-consumer:
          group-id: "likes"
        post-view-consumer:
          group-id: "post_views"

  config:
    import: text-gears-api.yaml

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  cache:
    caffeine:
      expireAfterAccess: 86400 # 24 часа

server:
  port: 8081

logging:
  level:
    root: info

services:
  s3:
    endpoint: http://127.0.0.1:9000
    accessKey: test
    secretKey: testtest
    bucketName: corpbucket
    region: eu-central-1
    isMocked: false
  grammar-checker:
    url: https://api.textgears.com
    apiKey: ${apiKey}
    dialects:
      "en": "en-US"
      "fr": "fr-FR"
      "de": "de-DE"
      "pt": "pt-PT"
      "it": "it-IT"
      "ru": "ru-RU"
      "ar": "ar-AR"
      "es": "es-ES"
      "ja": "ja-JP"
      "zh": "zh-CN"
      "el": "el-GR"

post:
  publisher:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute
  ad-remover:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute
  moderator:
    post-batch-size: 100
    scheduler:
      cron: "0 0 * * * ?" # every day
      dictionary:
        file: "classpath:moderation-dictionary.txt"
  constants:
    post-max-size: 1000
  grammar-checker:
    scheduler:
      cron: "0 0 0 * * ?" # every day
    attempts: 3
    delay: 1000
    multiplier: 2
  user-ban:
    cron: "0 0 0 * * ?" # every day
    post-limit: 5
    delay: 5000

comment:
  obscene-words-resource: obscene_words_resource/obscene-words.json
  verify-cron: "0 0 * * * ?" # every day at 00:00
  verify-batch: 10
  verify-task-executor:
    core-pool-size: 10
    max-pool-size: 20
    queue-capacity: 100
    thread-name-prefix: "verify-task-executor-"
  user-ban-cron: "0 0 * * * ?" # every day at 00:00
  user-ban-comment-limit: 5
  constants:
    verification-days-limit: 30

resource:
  max-size: 5242880
  max-count: 10
  image:
    max-rectangle-width: 1080
    max-rectangle-height: 566
    max-square-dimension: 1080

retryable:
  delay: 5000

user-service:
  host: 127.0.0.1
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080

feed:
  feed:
    default-feed-amount: 20
    #issued-feed-size: 100
    cache:
      max-cache-size: 500
    retry:
      max-attempts: 3
      delay: 800
  comment:
    default-comment-amount: 5
    cache:
      max-cache-size: 10
    retry:
      max-attempts: 3
      delay: 800
  like:
    default-like-amount: 5
    cache:
      max-cache-size: 10
    retry:
      max-attempts: 3
      delay: 800

  post-view:
    default-post-view-amount: 5
    cache:
      max-cache-size: 5
    retry:
      max-attempts: 3
      delay: 800