spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka1:
    bootstrap-servers: "localhost:9092"
    pool-size: 1
    producer:
      transactional-id: "post-service-transaction-id"
      acks: all
      enable-idempotence: true
      retries: 20
      max-in-flight-requests-per-connection: 1
    consumer:
      group-id: "group"
      auto-offset-reset: earliest
      enable-auto-commit: false
      isolation-level: read_committed
    topics:
      publish-post:
        name: publish-post
        num-partitions: 1
        replication-factor: 1
      likes:
        name: like
        num-partitions: 1
        replication-factor: 1
      comments:
        name: comment
        num-partitions: 1
        replication-factor: 1
      post-view:
        name: post-view
        num-partitions: 1
        replication-factor: 1


  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        calculations_channel: calculations_channel
        comment_channel: comment_channel
        like_channel: like_channel


server:
  port: 8081

logging:
  level:
    root: info

post:
  publisher:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute
  ad-remover:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute

user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080

services:
  s3:
    endpoint: http://127.0.0.1:9000
    accessKey: user
    secretKey: password
    bucketName: corpbucket

cache:
  post:
    live-time: 86400
  author:
    live-time: 86400
  comment:
    live-time: 1
    time-unit: DAYS
    set-key: comment

test: 10