spring:
  data:
    redis:
      port:
      host:
      postTtl: 24
      postPrefix: "Post"
      defaultTtl: 12 # hours
      commentTtl: 24 # hours

kafka:
  producerConfig:
    bootstrapServersConfig: localhost:9092
    acks: "all"
    retries: 5
    idempotence: true
  consumerConfig:
    bootstrapServersConfig: localhost:9092
    groupId: "kafka-group"
    autoOffsetReset: "earliest"
    autoCommit: false
    maxPollRecords: 100
    trustedPackages: "*"
  topics:
    postLikeTopic:
      name: post_likes
      numPartitions: 5
      replicationFactor: 1
    commentLikeTopic:
      name: comment_likes
      numPartitions: 5
      replicationFactor: 1