spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      transaction:
        retry:
          max-attempts: 5
          backoff:
            delay: 1000
      channels:
        calculations-channel: calculations_channel
        user-service: ban_user_channel
        like-service: like-event-channel
      topics:
        comment_event_topic: commentEventQueue

  kafka:
    bootstrap-servers: "localhost:9092"
    pool-size: 3
    consumer:
      group-id: "group"
      auto-offset-reset: earliest
    topics:
      album-created:
        name: album-created_topic
        num-partitions: 3
        replication-factor: 1
      post-for-feed:
        name: post_for_feed_topic
        num-partitions: 3
        replication-factor: 1
      comment-for-feed:
        name: comment-for-feed_topic
        num-partitions: 3
        replication-factor: 1

server:
  port: 8081
  news:
    feed:
      thread:
        pool:
          corePoolSize: 4
          maximumPoolSize: 10
          keepAliveTime: 60
          queueCapacity: 100
mock:
  user-service:
    client:
      enabled: true

logging:
  level:
    root: info

post:
  cache:
    count-hours-time-to-live: 24
    news-feed-size: 500
  publisher:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute
      size_batch: 100
  ad-remover:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute
  ban-user:
    scheduler:
      cron: "0 0 2 * * *" # every day
  verify:
    retry:
      max-attempts: 3
      delay: 5000
    scheduler:
      cron: "0 0 2 * * *" # every day
  thread-pool:
    count_pool: 10

user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080

censorship:
  words:
    - 1C
    - Динамическая типизация
    - Многопоточность