spring:
  data:
    kafka:
      producerConfig:
        bootstrapServersConfig: localhost:9092
        acks: "all"
        retries: 5
        idempotence: true
      topics:
        likeTopic:
          name: likes
          numPartitions: 5
          replicationFactor: 1