spring:
  mvc:
    servlet:
      path: /api/v1
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        calculations_channel:
          name: calculations_channel
        user_ban_channel:
          name: user_ban

server:
  port: 8081

logging:
  level:
    root: info

user-service:
  host: localhost
  port: 8080
  path: /api/v1
project-service:
  host: localhost
  port: 8082
  path: /api/v1
payment-service:
  host: localhost
  port: 9080

cron:
  expression: 0 16 12 * * ?

count:
  default: 0
  add: 1
  ban: 5


