spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  profiles:
    active: dev

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 50MB

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        calculations_channel:
          name: calculations_channel

  async:
    pool-size: 10
    max-pool-size: 10
    queue-capacity: 1000
    thread-name-prefix: "task-executor-thread-"

  scheduler:
    post:
      publisher:
        cron: 1/5 * * * * *
        partition-size: 1000

server:
  port: 8081

logging:
  level:
    root: info

services:
  s3:
    endpoint: http://localhost:9000
    accessKey: user
    secretKey: password
    bucketName: resource-post

user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080


