spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        calculationsChannel:
          name: calculations_channel
        commentChannel:
          name: comment_channel
        likePostChannel:
          name: like_post_channel
        newCommentChannel:
          name: new_comment_channel
        postViewChannel:
          name: post_view_channel
        userBanChannel:
          name: user_ban_channel
  kafka:
    bootstrapServers: localhost:9092
    consumer:
      groupId: example_group
      autoOffsetReset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic:
      post:
        name: post
        partitions: 1
        replicationFactor: 1

server:
  port: 8081

logging:
  level:
    root: info

post:
  executor:
    threads:
      count: 5
  publisher:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute
  ad-remover:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute
  moderation:
    scheduler:
      cron: "0 0 * * * ?" # every day at 00:00
    dictionary:
      file-path: "src/main/resources/moderation/dictionary.txt"
    sublist:
      length: 10
  author-banner:
    schedule:
      cron: "0 0/10 * * * ?" # event 10 minutes
    unverified-posts-limit: 5
    unverified-posts-days: 30

user-service:
  host: localhost
  port: 8080
  requiredHeaders: x-user-id
project-service:
  host: localhost
  port: 8082
  requiredHeaders: x-user-id
payment-service:
  host: localhost
  port: 9080
  requiredHeaders: x-user-id

moderate:
  comments:
    initialDelay: 5000
    fixedDelay: 3600000

dictionary:
  offensive:
    initial: "dictionary/offensive-words.yaml"
    remote:
      url: https://raw.githubusercontent.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words/refs/heads/master
      scheduler:
        cron: "0 0 0/24 * * *" # every 24 hours
    update:
      retry:
        maxAttempts: 2
        maxDelay: 1000
services:
  s3:
    endpoint: http://127.0.0.1:9000
    accessKey: user
    secretKey: password
    bucketName: corpbucket
    connectionTimeout: 50_000
    socketTimeout: 50_000

executor:
  capacity: 10
  corePoolSize: 1
  maximumPoolSize: 10
  keepAliveTime: 60

batchSize:
  BatchSizeSubscribers: 100

thread-pool-config:
  size: 4