spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  profiles:
    active: dev

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 50MB

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      user-ban-topic: user_ban

      channels:
        calculations_channel:
          name: calculations_channel

server:
  port: 8081

logging:
  level:
    root: info

services:
  s3:
    endpoint: http://192.168.1.100:9000
    accessKey: user
    secretKey: password
    bucketName: resource-post

user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080


cron:
  expression:
    ban-comments: "0 0 0 * * ?"

