spring:
  data:
    kafka:
      producerConfig:
        bootstrapServersConfig: localhost:9092
        acks: "all"
        retries: 5
        idempotence: true
      topics:
        PostLikeTopic:
          name: comment_likes
          numPartitions: 5
          replicationFactor: 1
        CommentLikeTopic:
          name: post_likes
          numPartitions: 5
          replicationFactor: 1